server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root4510@
  freemarker:
    allow-request-override: true
    cache: false
    charset: UTF-8
    content-type: text/html
#    prefix: classpath:template/
    suffix: .ftl
    template-loader-path: classpath:/template/
